Run ./gradlew clean assembleDebug --no-daemon To honour the JVM settings for this build a single-use Daemon process will be forked. For more on this, please refer to https://docs.gradle.org/8.4/userguide/gradle_daemon.html#sec:disabling_the_daemon in the Gradle documentation. Daemon will be stopped at the end of the build > Task :clean > Task :app:clean UP-TO-DATE > Task :app:preBuild UP-TO-DATE > Task :app:preDebugBuild UP-TO-DATE > Task :app:mergeDebugNativeDebugMetadata NO-SOURCE > Task :app:checkKotlinGradlePluginConfigurationErrors > Task :app:generateDebugResValues > Task :app:checkDebugAarMetadata > Task :app:mapDebugSourceSetPaths > Task :app:generateDebugResources > Task :app:packageDebugResources > Task :app:mergeDebugResources > Task :app:createDebugCompatibleScreenManifests > Task :app:extractDeepLinksDebug > Task :app:parseDebugLocalResources
> Task :app:processDebugMainManifest
package="com.cybertrail.app" found in source AndroidManifest.xml: /home/runner/work/CyberTrail/CyberTrail/android/app/src/main/AndroidManifest.xml.
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
Recommendation: remove package="com.cybertrail.app" from the source AndroidManifest.xml: /home/runner/work/CyberTrail/CyberTrail/android/app/src/main/AndroidManifest.xml.

> Task :app:processDebugManifest
> Task :app:javaPreCompileDebug
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets
> Task :app:desugarDebugFileDependencies
> Task :app:compressDebugAssets
> Task :app:checkDebugDuplicateClasses
> Task :app:mergeDebugJniLibFolders
> Task :app:processDebugManifestForPackage
> Task :app:mergeLibDexDebug
> Task :app:mergeDebugNativeLibs
> Task :app:processDebugResources
> Task :app:validateSigningDebug
> Task :app:mergeExtDexDebug
> Task :app:writeDebugAppMetadata
> Task :app:writeDebugSigningConfigVersions

> Task :app:stripDebugDebugSymbols
Unable to strip the following libraries, packaging them as they are: libcybertrail_ffi.so, libmapbox-gl.so.

e: file:///home/runner/work/CyberTrail/CyberTrail/android/app/src/main/java/com/cybertrail/app/MapActivity.kt:50:20 None of the following functions can be called with the arguments supplied: 
public open fun getInstance(p0: Context): Mapbox defined in com.mapbox.mapboxsdk.Mapbox
public open fun getInstance(p0: Context, p1: String?, p2: WellKnownTileServer!): Mapbox defined in com.mapbox.mapboxsdk.Mapbox
e: file:///home/runner/work/CyberTrail/CyberTrail/android/app/src/main/java/com/cybertrail/app/MapActivity.kt:130:29 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type LatLng?
e: file:///home/runner/work/CyberTrail/CyberTrail/android/app/src/main/java/com/cybertrail/app/MapActivity.kt:131:29 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type LatLng?
> Task :app:compileDebugKotlin FAILED

30 actionable tasks: 29 executed, 1 up-to-date
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 17s
Error: Process completed with exit code 1.
0s